baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "My New Hugo Site"

# RSS config
copyright = "Kathrine Borup"

[author]
    name = "Kathrine Borup"

# Main menu config
[[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about"

#[[menu.main]]
#    name = "my handmade closet"
#    weight = 2
#    identifier = "closet"
#    url = "/closet"

[[menu.main]]
    name = "links"
    weight = 3
    identifier = "links"
    url = "/links"

#[[menu.main]]
#    name = "archive"
#    weight = 4
#    identifier = "archive"
#    url = "/archive"
